name: Create Archive

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove old archive
        run: rm -f release.zip

      - name: Create ZIP archive
        uses: thedoctor0/zip-release@master
        with:
          filename: release.zip
          exclusions: '*.git* /*node_modules/* .github/*'

      - name: Commit and push archive
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add release.zip
          git commit -m "Update resource pack archive" || echo "No changes"
          git push
